### ISSUE TITLE
Проигрыватель

### ISSUE THREAD

**Issue by vanja-san** [ruslanys/vkmusic#35]
Увидит ли это приложение в будующем встроенный муз. проигрыватель? Очень бы хотелось чтобы проигрыватель появился, чтобы не только скачивать можно было, но и прослушивать!
Приложение супер! 👱‍♂️👍
![2019-03-29-19-29-28](https://user-images.githubusercontent.com/7201687/55232746-0458b480-5259-11e9-8a42-a126c9a371a7.png)

**Comment by ruslanys** [comment]
Здравствуй, @vanja-san! Большое спасибо за обратную связь, это очень приятно. 
Насчет проигрывателя пока не знаю. По правде говоря, сделать хороший проигрыватель – практически бесконечный путь разработки, с другой стороны, задумывался об этом уже. 

В любом случае, теперь я знаю, что есть пользователи, которым это нужно. :) 

В общем, пускай повисит пока задачка, соберусь делать, придет уведомление; решу, что точно не будет – закрою задачу.

Успехов! 😉
